import test from 'node:test';import assert from 'node:assert/strict';import net from 'node:net';import {mkdtemp,mkdir,writeFile,readFile,readdir} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomBytes} from 'node:crypto';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';import {decode} from '@toon-format/toon';
const restore=result=>{const text=result.content[0].text;return text.startsWith('TOON:')?decode(text.slice(text.indexOf('\n')+1)):JSON.parse(text);};
test('real MCP stdio uses pinned state, single-copy payloads and bounded context',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'comm-mcp-sdk-')),runtime=path.join(root,'target','test'),records=path.join(runtime,'recordings','r');await mkdir(records,{recursive:true});
 const token=randomBytes(32).toString('base64url');let dispatches=0;const peers=new Set();
 const state=(id,hp=63)=>({type:'state',session_id:'s',state_id:id,ready:true,runtime:{language:'KOR'},actions:[{id:'run.event.0',label:'떠난다',parameters:{}}],observation:{game_state:{screen_type:'EVENT',current_hp:hp,deck:[{name:'타격'},{name:'방어'}],mechanics:{collection:{count:135,cards_complete:true,order_visible:false,cards:Array.from({length:135},(_,i)=>({id:`card-${i}`}))}},screen_state:{body_text:'이벤트 본문 전체',options:[{text:'떠난다'}]}}}});
 const backend=net.createServer(socket=>{peers.add(socket);socket.on('close',()=>peers.delete(socket));socket.setEncoding('utf8');let buffer='',auth=false;socket.on('data',data=>{buffer+=data;for(let i;(i=buffer.indexOf('\n'))>=0;){const m=JSON.parse(buffer.slice(0,i));buffer=buffer.slice(i+1);if(!auth){assert.equal(m.token,token);auth=true;socket.write(JSON.stringify({type:'bridge_ready'})+'\n');setTimeout(()=>socket.write(JSON.stringify(state(1))+'\n'),20);}else{dispatches++;socket.write(JSON.stringify({type:'result',request_id:m.request_id,status:'applied'})+'\n');socket.write(JSON.stringify({...state(2),ready:false,actions:[]})+'\n');setTimeout(()=>socket.write(JSON.stringify(state(3))+'\n'),15);}}});});
 await new Promise(r=>backend.listen(0,'127.0.0.1',r));await writeFile(path.join(root,'target','local-test-ready.json'),JSON.stringify({runtime}));await writeFile(path.join(records,'mcp-bridge.json'),JSON.stringify({protocol:1,port:backend.address().port,token}));
 const client=new Client({name:'test-client',version:'1'}),transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/index.js')],env:{...process.env,COMMUNICATIONMOD_WORKSPACE:root,COMMUNICATIONMOD_METRICS:'1'},stderr:'pipe'}),publish=message=>{for(const p of peers)p.write(JSON.stringify(message)+'\n');};
 try{
  await client.connect(transport);const tools=(await client.listTools()).tools;assert.equal(tools.length,6);const actSchema=tools.find(t=>t.name==='sts_act').inputSchema,ctxSchema=tools.find(t=>t.name==='sts_get_context').inputSchema;
  for(const schema of [actSchema,ctxSchema]){assert.equal(schema.properties.session_id,undefined);assert.equal(schema.properties.state_id,undefined);}assert.deepEqual(Object.keys(actSchema.properties).sort(),['action_id','arguments']);
  const get=restore(await client.callTool({name:'sts_get_state',arguments:{wait_ms:1000}}));assert.equal(get.screen_state.body_text,'이벤트 본문 전체');for(const key of ['session_id','state_id','connection','ready'])assert.equal(get[key],undefined,key);assert.ok(get.toc.some(x=>x.ref==='screen'));assert.ok(!get.toc.some(x=>x.ref==='map'));
  assert.deepEqual(restore(await client.callTool({name:'sts_get_state',arguments:{known_view:get.view_id}})),{view_id:get.view_id,unchanged:true});
  const waitStarted=performance.now(),waited=restore(await client.callTool({name:'sts_get_state',arguments:{known_view:get.view_id,wait_ms:80}}));assert.ok(performance.now()-waitStarted>=65);assert.equal(waited.unchanged,true);
  const change=setTimeout(()=>publish(state(1,64)),30);try{assert.equal(restore(await client.callTool({name:'sts_get_state',arguments:{known_view:get.view_id,wait_ms:1000}})).player.current_hp,64);}finally{clearTimeout(change);}
  publish(state(1));const repinned=restore(await client.callTool({name:'sts_get_state',arguments:{wait_ms:0}}));const controller=new AbortController(),cancelled=client.callTool({name:'sts_get_state',arguments:{known_view:repinned.view_id,wait_ms:15000}},undefined,{signal:controller.signal}),rejected=assert.rejects(cancelled),cancelTimer=setTimeout(()=>controller.abort('test cancellation'),80);try{await rejected;}finally{clearTimeout(cancelTimer);}
  const exampleRef=repinned.guidance?.ref;if(exampleRef)assert.ok(restore(await client.callTool({name:'sts_get_context',arguments:{refs:[exampleRef]}})).fragments[0].data);
  const mechanics=restore(await client.callTool({name:'sts_get_context',arguments:{refs:['mechanics']}}));assert.ok(mechanics.fragments[0].toc.some(x=>x.ref==='mechanics/collection'));
  const tail=restore(await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards'],offset:130,limit:30}}));assert.equal(tail.fragments[0].toc[4].title,'card-134');assert.equal(tail.fragments[0].next_offset,undefined);
  const batch=restore(await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards/134','deck/0']}}));assert.equal(batch.fragments[0].data.id,'card-134');assert.equal(batch.fragments[1].data.name,'타격');assert.ok(Buffer.byteLength(JSON.stringify(batch),'utf8')<5000);
  const compactResult=await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards'],limit:20,response_format:'compact'}});assert.equal(compactResult.structuredContent,undefined);assert.deepEqual(restore(compactResult),restore(await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards'],limit:20}})));assert.equal((await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards'],response_format:'tsv'}})).isError,true);
  const result=restore(await client.callTool({name:'sts_act',arguments:{action_id:'run.event.0'}}));assert.deepEqual(Object.keys(result),['state']);assert.equal(dispatches,1);assert.equal(result.state.session_id,undefined);assert.equal(result.state.state_id,undefined);
  publish(state(4));await new Promise(r=>setTimeout(r,10));assert.equal((await client.callTool({name:'sts_act',arguments:{action_id:'run.event.0'}})).isError,true);assert.equal(dispatches,1);assert.equal((await client.callTool({name:'sts_get_context',arguments:{refs:['collection/cards']}})).isError,true);
  const fresh=restore(await client.callTool({name:'sts_get_state',arguments:{wait_ms:0}}));assert.ok(fresh.view_id);const deck=restore(await client.callTool({name:'sts_get_context',arguments:{refs:['deck'],limit:1}}));assert.equal(deck.fragments[0].total,2);assert.equal(deck.fragments[0].next_offset,1);
  assert.deepEqual(restore(await client.callTool({name:'sts_get_request',arguments:{request_id:'definitely-missing'}})),{status:'unknown'});
  const metricsDir=path.join(root,'target','agent-efficiency','metrics');let rows=[];for(let i=0;i<40;i++){try{const files=(await readdir(metricsDir)).filter(x=>x.endsWith('.jsonl'));rows=(await Promise.all(files.map(f=>readFile(path.join(metricsDir,f),'utf8')))).flatMap(text=>text.trim().split('\n').filter(Boolean).map(JSON.parse));}catch{}if(rows.some(r=>r.error_class==='cancelled'))break;await new Promise(r=>setTimeout(r,10));}
  assert.ok(rows.some(r=>r.tool==='sts_get_state'&&r.wait_ms>=65));assert.ok(rows.some(r=>r.tool==='sts_get_state'&&r.error_class==='cancelled'));assert.ok(rows.every(r=>r.response_bytes>0));assert.ok(!JSON.stringify(rows).includes('이벤트 본문'));assert.ok(!JSON.stringify(rows).includes(token));
 }finally{await client.close();for(const socket of peers)socket.destroy();await new Promise(r=>backend.close(r));}
});
