import test from 'node:test';import assert from 'node:assert/strict';import net from 'node:net';import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomBytes} from 'node:crypto';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
test('real MCP stdio tool discovery, focused state, action+next state and context pagination',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'comm-mcp-sdk-'));const runtime=path.join(root,'target','test');const records=path.join(runtime,'recordings','r');await mkdir(records,{recursive:true});
 const token=randomBytes(32).toString('base64url');let dispatches=0;const peers=new Set();
 const state=id=>({type:'state',session_id:'s',state_id:id,ready:true,runtime:{language:'KOR'},actions:[{id:'run.event.0',label:'떠난다',parameters:{}}],observation:{game_state:{screen_type:'EVENT',current_hp:63,deck:[{name:'타격'},{name:'방어'}],screen_state:{body_text:'이벤트 본문 전체',options:[{text:'떠난다'}]}}}});
 const backend=net.createServer(socket=>{peers.add(socket);socket.on('close',()=>peers.delete(socket));socket.setEncoding('utf8');let buffer='',auth=false;socket.on('data',data=>{buffer+=data;for(let i;(i=buffer.indexOf('\n'))>=0;){const m=JSON.parse(buffer.slice(0,i));buffer=buffer.slice(i+1);if(!auth){assert.equal(m.token,token);auth=true;socket.write(JSON.stringify({type:'bridge_ready'})+'\n');setTimeout(()=>socket.write(JSON.stringify({type:'result',request_id:'previous',status:'applied'})+'\n'),20);setTimeout(()=>socket.write(JSON.stringify(state(1))+'\n'),60);}else{dispatches++;socket.write(JSON.stringify({type:'result',request_id:m.request_id,status:'applied'})+'\n');socket.write(JSON.stringify({...state(2),ready:false,actions:[]})+'\n');setTimeout(()=>socket.write(JSON.stringify(state(3))+'\n'),15);}}});});
 await new Promise(r=>backend.listen(0,'127.0.0.1',r));await writeFile(path.join(root,'target','local-test-ready.json'),JSON.stringify({runtime}));await writeFile(path.join(records,'mcp-bridge.json'),JSON.stringify({protocol:1,port:backend.address().port,token}));
 const client=new Client({name:'test-client',version:'1'});const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('dist/index.js')],env:{...process.env,COMMUNICATIONMOD_WORKSPACE:root},stderr:'pipe'});
 try{await client.connect(transport);const tools=(await client.listTools()).tools;assert.equal(tools.length,6);assert.ok(tools.some(t=>t.name==='sts_start_game'));assert.ok(tools.some(t=>t.name==='sts_game_status'));
  const get=await client.callTool({name:'sts_get_state',arguments:{wait_ms:1000}});assert.equal(get.structuredContent.data.screen_state.body_text,'이벤트 본문 전체');assert.equal(get.structuredContent.data.deck,undefined);
  const result=await client.callTool({name:'sts_act',arguments:{session_id:'s',state_id:1,action_id:'run.event.0',request_id:'one'}});assert.equal(result.structuredContent.data.state.state_id,3);assert.equal(result.structuredContent.data.outcome,'applied');
  const stale=await client.callTool({name:'sts_act',arguments:{session_id:'s',state_id:1,action_id:'run.event.0'}});assert.equal(stale.isError,true);assert.equal(dispatches,1);
  const deck=await client.callTool({name:'sts_get_context',arguments:{session_id:'s',state_id:3,section:'deck',limit:1}});assert.equal(deck.structuredContent.data.total,2);assert.equal(deck.structuredContent.data.next_offset,1);
 }finally{await client.close();for(const socket of peers)socket.destroy();await new Promise(r=>backend.close(r));}
});
