import test from 'node:test';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';import {Tiktoken} from 'js-tiktoken/lite';import ranks from 'js-tiktoken/ranks/o200k_base';import {readContext} from '../dist/context.js';import {Lifecycle} from '../dist/lifecycle.js';
const tokenizer=new Tiktoken(ranks),count=value=>tokenizer.encode(JSON.stringify(value),[],[]).length,state=screen_type=>({session_id:'s',state_id:1,ready:true,connection:{status:'connected',pending_request_id:null},actions:[],observation:{game_state:{screen_type,current_hp:20,combat_state:{turn:1}},reward_navigation:{unclaimed_rewards:2}}});
test('tool schemas hide transport identity and default to automatic lossless compact context',async()=>{
 const client=new Client({name:'prose-audit',version:'1'});let tools;try{await client.connect(new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../dist/index.js',import.meta.url))],stderr:'pipe'}));tools=(await client.listTools()).tools;}finally{await client.close();}
 const byName=Object.fromEntries(tools.map(t=>[t.name,t]));for(const name of ['sts_act','sts_get_context']){assert.equal(byName[name].inputSchema.properties.session_id,undefined);assert.equal(byName[name].inputSchema.properties.state_id,undefined);}assert.equal(byName.sts_get_state.inputSchema.properties.known_view,undefined);assert.ok(byName.sts_get_state.inputSchema.properties.refresh);assert.deepEqual(Object.keys(byName.sts_act.inputSchema.properties).sort(),['action_id','arguments']);assert.equal(byName.sts_get_context.inputSchema.properties.response_format.default,'compact');
 const descriptions=Object.fromEntries(tools.map(t=>[t.name,t.description])),required={sts_game_status:[/process/i,/connection/i,/no launch/i,/no play/i],sts_start_game:[/verified test game/i,/user.*launch\/play request/i,/never.*resum/i,/never.*choos/i,/no relaunch/i],sts_get_state:[/current decision/i,/state.scoped toc/i,/server-side/i,/unchanged/i,/refresh/i,/TOON/i,/JSON/i],sts_act:[/one offered action/i,/pinned state/i,/never auto-discard/i,/unknown\/applied_waiting/i,/never replay/i,/next decision/i,/TOON/i],sts_get_context:[/1-8/i,/pinned state/i,/TOON/i,/JSON/i,/one card ref alone/i,/stale pin/i],sts_get_request:[/uncertain/i,/request_id/i,/without replay/i,/never resend/i]};
 for(const [name,patterns] of Object.entries(required))for(const pattern of patterns)assert.match(descriptions[name],pattern,`${name}: ${pattern}`);assert.ok(tools.every(t=>count({title:t.title,description:t.description})<220));
});
test('gameplay rules keep decision-critical safety without pinned identity chatter',()=>{
 const rules={};for(const screen of ['EVENT','MAP','COMBAT_REWARD','NONE']){const fragment=readContext(state(screen),['rules']).fragments[0];Object.assign(rules,fragment.data??{});for(const row of fragment.toc??[])rules[row.ref.split('/').at(-1)]=readContext(state(screen),[row.ref]).fragments[0].text;}
 const clauses={act:[/only offered actions/i,/current state/i,/one action per call/i,/never replay unknown\/applied_waiting/i,/refresh.*stale/i],cost:[/card\.costForTurn/i,/Snecko/i,/displayed_cost_text/i,/target_playability/i],upgrade:[/before acquisition or upgrade/i,/upgrade_preview/i,/next standard upgrade/i],event:[/event body/i,/server pins the current reading identity/i,/meaningful commentary/i,/result pages/i],map:[/draws route/i,/never moves character/i,/server pins map identity and revision/i,/native edges only/i],reward:[/reward_navigation/i,/unclaimed rewards/i,/never auto-discard/i]};for(const [name,patterns] of Object.entries(clauses))for(const pattern of patterns)assert.match(rules[name],pattern,`${name}: ${pattern}`);
 for(const forbidden of ['session_id','state_id','view_id','known_view','reading_id','map_id/revision'])assert.ok(!JSON.stringify(rules).includes(forbidden),forbidden);
});
test('startup safety remains explicit',async()=>{let launches=0;const lifecycle=new Lifecycle('fixture',{ensure:async()=>{},game:{current:()=>({connection:{status:'disconnected_or_stale'}})}},async()=>{launches++;return {phase:'running'};});const loading=await lifecycle.start(0);assert.equal(launches,1);assert.equal(loading.retry_launch,false);assert.match(loading.next_step,/sts_get_state or sts_game_status/);assert.match(loading.next_step,/no second game|do not start a second game/i);});
test('native text and exact errors are not rewritten by lean projection',async()=>{const card={id:'never/replay-X',name:'화염',description:'피해 12. 방어도 없으면 사용 불가. 최대 HP 3 감소.',displayed_cost_text:'X',cost_components:{energy:0,reserves:2},displayed_cost_complete:false,unplayable_reason:'Do not replay unknown outcomes.',upgrade_preview:{status:'unavailable',reason:'not rendered'}},s={...state('CARD_REWARD')};s.observation.game_state.screen_state={cards:[card],event_reading:{body_text:'선택 전: 골드 75 소모. 취소 불가.\n동의하지 않으면 떠난다.'}};assert.deepEqual(readContext(s,['screen/cards/0']).fragments[0].data,card);assert.equal(readContext(s,['screen/event_reading/body_text']).fragments[0].text,s.observation.game_state.screen_state.event_reading.body_text);assert.throws(()=>readContext(s,['full']),{message:'Reference not available in current state.'});const exact='Native error: never resend; request_id=abc; code=409',lifecycle=new Lifecycle('fixture',{ensure:async()=>{},game:{current:()=>({})}},async()=>{throw new Error(exact);});await assert.rejects(lifecycle.start(0),{message:exact});});
